services:
  practice-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practice-service
    ports:
      - "${PRACTICE_SERVICE_PORT:-8130}:8130"
    environment:
      # App
      APP_ENV: ${APP_ENV:-development}

      # MySQL
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}

      # MongoDB
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}

      # Storage
      CONTAINER_PATH: ${CONTAINER_PATH}
    volumes:
      - ${HOST_PATH}:${CONTAINER_PATH}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true